---
title: "Graphing for G-E Interplay on EXT Trajectories"
author: "LiChen Dong"
date: "`r lubridate::today()`"
format: 
  html: 
    embed-resources: true
    toc: true 
    toc_depth: 4
editor_options: 
  chunk_output_type: console
---


# Setup

```{r}
#| output: false

options(conflicts.policy = "depends.ok",
        digits = 3,
        pillar.sigfig = 0)
library(tidyverse)
library(lavaan)
library(MplusAutomation)

path_data <- "../data_local"
```

# EUR


## Read in output

```{r}
eur <- readModels(here::here("analysis/rnr_eur.out"))$parameters$ci.unstandardized |> 
          as_tibble() |> janitor::clean_names() |> 
          select(param_header, param, est, low_5, up_5)

eur$param_header[396:420] <- rep(c("ASB#1.ON", "ASB#2.ON", "ASB#3.ON","SUB#1.ON", "SUB#2.ON"), each = 5)
eur <- eur |> mutate(param = replace(param, param %in% c("INDASB11","INDASB21",
                                                         "INDASB31","INDSUB11","INDSUB21"), 
                                     "Parent Indirect Effect"),
                     param = replace(param, param %in% c("INDASB12","INDASB22",
                                                         "INDASB32","INDSUB12","INDSUB22"), 
                                     "Peer Indirect Effect"),
                     param = replace(param, param %in% c("INDASB13","INDASB23",
                                                         "INDASB33","INDSUB13","INDSUB23"), 
                                     "School Indirect Effect"),
                     param = replace(param, param %in% c("INDASB14","INDASB24",
                                                         "INDASB34","INDSUB14","INDSUB24"), 
                                     "Neighborhood Indirect Effect"),
                     param = replace(param, param %in% c("TOTALASB","TOTALSUB"), 
                                     "Total Effect"))

eur_apaths <- eur |> filter(param_header %in% c("PARENT.ON", "PEER.ON", "SCHOOL.ON", "NEIGHBOR.ON"))

eur_mainpaths <- eur |> filter(param_header %in% c("ASB#1.ON", "ASB#2.ON", 
                                                   "ASB#3.ON","SUB#1.ON", "SUB#2.ON"))
```



## Process a paths

```{r}
eur_apaths <- eur_apaths |> 
              rename(outcome = "param_header", variable = "param", lower = "low_5", upper = "up_5") |> 
              mutate(outcome = case_match(outcome, 
                                               "PARENT.ON" ~ "Supportive Parenting", 
                                               "PEER.ON" ~ "Delinquent Peer Affiliation", 
                                               "SCHOOL.ON" ~ "School Connectedness", 
                                               "NEIGHBOR.ON" ~ "Neighborhood Connectedness"),
                     variable = case_match(variable,
                                        "AGE" ~ "Age",
                                        "SEX" ~ "Female Sex",
                                        "INCOME" ~ "Family Income",
                                        "PARED" ~ "Parental Education",
                                        "WHITE" ~ "White",
                                        "NATIVE" ~ "Native",
                                        "OTHER" ~ "Other Race",
                                        "HISPANIC" ~ "Hispanic",
                                        "SINGLE_PAR" ~ "Single Parent",
                                        "PGS" ~ "PGS"),
                     variable = factor(variable, c("PGS", "Age", "Female Sex", "Family Income", "Parental Education", "Single Parent","White", "Native", "Other Race", "Hispanic"))) 
```

## Process main paths

```{r}
eur_mainpaths <- eur_mainpaths |> 
              rename(outcome = "param_header", variable = "param", lower = "low_5", upper = "up_5") |> 
              mutate(outcome = case_match(outcome, 
                                               "ASB#1.ON" ~ "High-Decline ASB", 
                                               "ASB#2.ON" ~ "Moderate ASB", 
                                               "ASB#3.ON" ~ "Adolescent-Peaked ASB", 
                                               "SUB#1.ON" ~ "High SUB",
                                               "SUB#2.ON" ~ "Low SUB"),
                     variable = case_match(variable,
                                        "PARENT" ~ "Supportive Parenting",
                                        "PEER" ~ "Delinquent Peer Affiliation",
                                        "SCHOOL" ~ "School Connectedness",
                                        "NEIGHBOR" ~ "Neighborhood Connectedness",
                                        "Total Effect" ~ "Total Effect",
                                        "Parent Indirect Effect" ~ "Parent Indirect Effect",
                                        "Peer Indirect Effect" ~ "Peer Indirect Effect",
                                        "School Indirect Effect" ~ "School Indirect Effect",
                                        "Neighborhood Indirect Effect" ~ "Neighborhood Indirect Effect",
                                        "PGS" ~ "PGS Direct Effect",
                                        "PGSPARENT" ~ "PGS x Parent",
                                        "PGSPEER" ~ "PGS x Peer",
                                        "PGSSCHOOL" ~ "PGS x School",
                                        "PGSNEIGHBO" ~ "PGS x Neighborhood",
                                        "AGE" ~ "Age",
                                        "SEX" ~ "Female Sex",
                                        "INCOME" ~ "Family Income",
                                        "PARED" ~ "Parental Education",
                                        "SINGLE_PAR" ~ "Single Parent",
                                        "WHITE" ~ "White",
                                        "NATIVE" ~ "Native",
                                        "OTHER" ~ "Other Race",
                                        "HISPANIC" ~ "Hispanic",
                                        "PGSAGE" ~ "PGS x Age",
                                        "PGSSEX" ~ "PGS x Sex",
                                        "PGSINC" ~ "PGS x Income",
                                        "PGSPARED" ~ "PGS x Parental Education",
                                        "PGSSINGPAR" ~ "PGS x Single Parent",
                                        "SUB_HI_DUM" ~ "High SUB",
                                        "SUB_LO_DUM" ~ "Low SUB",
                                        "ASB_HI_DUM" ~ "High-Decline ASB",
                                        "ASB_MOD_DU" ~ "Moderate ASB",
                                        "ASB_ADO_DU"  ~ "Adolescent-Peaked ASB"
                                          ),
                     variable = factor(variable, c(
                                        "Supportive Parenting",
                                        "Delinquent Peer Affiliation",
                                        "School Connectedness",
                                        "Neighborhood Connectedness",
                                        "Total Effect",
                                        "Parent Indirect Effect",
                                        "Peer Indirect Effect",
                                        "School Indirect Effect",
                                        "Neighborhood Indirect Effect",
                                        "PGS Direct Effect",
                                        "PGS x Parent",
                                        "PGS x Peer",
                                        "PGS x School",
                                        "PGS x Neighborhood",
                                        "Age",
                                        "Female Sex",
                                        "Family Income",
                                        "Parental Education",
                                        "Single Parent",
                                        "White",
                                        "Native",
                                        "Other Race",
                                        "Hispanic",
                                        "PGS x Age",
                                        "PGS x Sex",
                                        "PGS x Income",
                                        "PGS x Parental Education",
                                        "PGS x Single Parent",
                                        "High SUB",
                                        "Low SUB",
                                        "High-Decline ASB",
                                        "Moderate ASB",
                                        "Adolescent-Peaked ASB"

                     ))) 
```


## EUR plots

### Interaction 

```{r}
plot_int <- eur_mainpaths |> filter(variable %in% c("PGS x Parent",
                                                    "PGS x Peer",
                                                    "PGS x School",
                                                    "PGS x Neighborhood")) |> 
            mutate(outcome = factor(outcome,
                                    c("High SUB",
                                      "Low SUB",
                                      "High-Decline ASB",
                                      "Moderate ASB",
                                      "Adolescent-Peaked ASB"
)),
                   est = exp(est),
                   lower = exp(lower),
                   upper = exp(upper),
                   sig = if_else(log(lower)*log(upper) >= 0, 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "*"), 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "")))

plot_all_int <- ggplot(data = plot_int) + 
  geom_point(aes(x = est,y = variable), shape = 23, size = 1.2, stroke = 1.2, fill = "black") + 
  geom_vline(xintercept = 1, color = "red",linetype = "dashed",linewidth = .25) +
  geom_errorbar(aes(y = variable, xmin = lower, xmax = upper),width=.3,linewidth = .55) + 
  geom_text(aes(x = est, y = variable, label = sig),vjust = -.9) +
  facet_grid(cols = vars(outcome)) + coord_cartesian(xlim = c(0.5,1.75)) +theme_bw() +
  scale_y_discrete(limits=rev) + 
  scale_x_continuous(breaks = seq(0.5, 1.75, by = .25))+
  theme(text = element_text(size = 9),
        axis.text.x = element_text(size = 9),
        axis.text.y = element_text(size = 9),  
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        strip.text = element_text(size = 10)) +
  labs(x = "Odds Ratio (99% CI)")
plot_all_int

ggsave("plot_all_int.jpg", plot_all_int, width = 15, height = 2.6, dpi = 300)
```

### Mediation

```{r}
plot_med <- eur_mainpaths |> filter(variable %in% c("PGS Direct Effect",
                                                    "Parent Indirect Effect",
                                                    "Peer Indirect Effect",
                                                    "School Indirect Effect",
                                                    "Neighborhood Indirect Effect",
                                                    "Total Effect")) |> 
            mutate(outcome = factor(outcome,
                                    c("High SUB",
                                      "Low SUB",
                                      "High-Decline ASB",
                                      "Moderate ASB",
                                      "Adolescent-Peaked ASB"
)),
                   est = exp(est),
                   lower = exp(lower),
                   upper = exp(upper),
                   sig = if_else(log(lower)*log(upper) >= 0, 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "*"), 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "")))

plot_all_med <- ggplot(data = plot_med) + 
  geom_point(aes(x = est,y = variable), shape = 23, size = 1.2, stroke = 1.2, fill = "black") + 
  geom_vline(xintercept = 1, color = "red",linetype = "dashed",linewidth = .25) +
  geom_errorbar(aes(y = variable, xmin = lower, xmax = upper),width=.3,linewidth = .55) + 
  geom_text(aes(x = est, y = variable, label = sig),vjust = -.9) +
  facet_grid(cols = vars(outcome)) + coord_cartesian(xlim = c(0.65,2.05)) +theme_bw() +
  scale_y_discrete(limits=rev) + 
  scale_x_continuous(breaks = seq(0.5, 2.5, by = .25))+
  theme(text = element_text(size = 9),
        axis.text.x = element_text(size = 9),
        axis.text.y = element_text(size = 9),  
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        strip.text = element_text(size = 10)) +
  labs(x = "Odds Ratio (99% CI)")
plot_all_med

ggsave("plot_all_med.jpg", plot_all_med, width = 15, height = 3.8, dpi = 300)

```


## EUR table

```{r}
eur_apaths <- eur_apaths |> 
  mutate(outcome = factor(outcome,
                                    c("Supportive Parenting",
                                      "Delinquent Peer Affiliation",
                                      "School Connectedness",
                                      "Neighborhood Connectedness"
)),
                   est = if_else(lower*upper >= 0, 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "*"), 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "")),
                   lower = sprintf("%.3f", round(lower, digits = 3)),
                   upper = sprintf("%.3f", round(upper, digits = 3))
) |> arrange(outcome, variable)

eur_mainpaths <- eur_mainpaths |> 
  mutate(outcome = factor(outcome,
                                    c("High SUB",
                                      "Low SUB",
                                      "High-Decline ASB",
                                      "Moderate ASB",
                                      "Adolescent-Peaked ASB"
)),
                   est = exp(est),
                   lower = exp(lower),
                   upper = exp(upper),
                   est = if_else(log(lower)*log(upper) >= 0, 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "*"), 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "")),
                   lower = sprintf("%.3f", round(lower, digits = 3)),
                   upper = sprintf("%.3f", round(upper, digits = 3))
)|> arrange(outcome, variable)

write_csv(eur_apaths, "eur_apaths.csv")
write_csv(eur_mainpaths, "eur_mainpaths.csv")
```


# AFR

## Read in output

```{r}
afr <- readModels(here::here("analysis/rnr_afr.out"))$parameters$ci.unstandardized |> 
          as_tibble() |> janitor::clean_names() |> 
          select(param_header, param, est, low_5, up_5)

afr$param_header[426:450] <- rep(c("ASB#1.ON", "ASB#2.ON", "ASB#3.ON","SUB#1.ON", "SUB#2.ON"), each = 5)
afr <- afr |> mutate(param = replace(param, param %in% c("INDASB11","INDASB21",
                                                         "INDASB31","INDSUB11","INDSUB21"), 
                                     "Parent Indirect Effect"),
                     param = replace(param, param %in% c("INDASB12","INDASB22",
                                                         "INDASB32","INDSUB12","INDSUB22"), 
                                     "Peer Indirect Effect"),
                     param = replace(param, param %in% c("INDASB13","INDASB23",
                                                         "INDASB33","INDSUB13","INDSUB23"), 
                                     "School Indirect Effect"),
                     param = replace(param, param %in% c("INDASB14","INDASB24",
                                                         "INDASB34","INDSUB14","INDSUB24"), 
                                     "Neighborhood Indirect Effect"),
                     param = replace(param, param %in% c("TOTALASB","TOTALSUB"), 
                                     "Total Effect"))

afr_apaths <- afr |> filter(param_header %in% c("PARENT.ON", "PEER.ON", "SCHOOL.ON", "NEIGHBOR.ON"))

afr_mainpaths <- afr |> filter(param_header %in% c("ASB#1.ON", "ASB#2.ON", 
                                                   "ASB#3.ON","SUB#1.ON", "SUB#2.ON"))

```

## Process a paths

```{r}
afr_apaths <- afr_apaths |> 
              rename(outcome = "param_header", variable = "param", lower = "low_5", upper = "up_5") |> 
              mutate(outcome = case_match(outcome, 
                                               "PARENT.ON" ~ "Supportive Parenting", 
                                               "PEER.ON" ~ "Delinquent Peer Affiliation", 
                                               "SCHOOL.ON" ~ "School Connectedness", 
                                               "NEIGHBOR.ON" ~ "Neighborhood Connectedness"),
                     variable = case_match(variable,
                                        "AGE" ~ "Age",
                                        "SEX" ~ "Female Sex",
                                        "INCOME" ~ "Family Income",
                                        "PARED" ~ "Parental Education",
                                        "WHITE" ~ "White",
                                        "AFRICAN" ~ "African",
                                        "NATIVE" ~ "Native",
                                        "OTHER" ~ "Other Race",
                                        "HISPANIC" ~ "Hispanic",
                                        "SINGLE_PAR" ~ "Single Parent",
                                        "PGS" ~ "PGS"),
                     variable = factor(variable, c("PGS", "Age", "Female Sex", "Family Income", "Parental Education", "Single Parent","White", "African", "Native", "Other Race", "Hispanic"))) 

```


## Process main paths

```{r}
afr_mainpaths <- afr_mainpaths |> 
              rename(outcome = "param_header", variable = "param", lower = "low_5", upper = "up_5") |> 
              mutate(outcome = case_match(outcome, 
                                               "ASB#1.ON" ~ "High-Decline ASB", 
                                               "ASB#2.ON" ~ "Moderate ASB", 
                                               "ASB#3.ON" ~ "Adolescent-Peaked ASB", 
                                               "SUB#1.ON" ~ "High SUB",
                                               "SUB#2.ON" ~ "Low SUB"),
                     variable = case_match(variable,
                                        "PARENT" ~ "Supportive Parenting",
                                        "PEER" ~ "Delinquent Peer Affiliation",
                                        "SCHOOL" ~ "School Connectedness",
                                        "NEIGHBOR" ~ "Neighborhood Connectedness",
                                        "Total Effect" ~ "Total Effect",
                                        "Parent Indirect Effect" ~ "Parent Indirect Effect",
                                        "Peer Indirect Effect" ~ "Peer Indirect Effect",
                                        "School Indirect Effect" ~ "School Indirect Effect",
                                        "Neighborhood Indirect Effect" ~ "Neighborhood Indirect Effect",
                                        "PGS" ~ "PGS Direct Effect",
                                        "PGSPARENT" ~ "PGS x Parent",
                                        "PGSPEER" ~ "PGS x Peer",
                                        "PGSSCHOOL" ~ "PGS x School",
                                        "PGSNEIGHBO" ~ "PGS x Neighborhood",
                                        "AGE" ~ "Age",
                                        "SEX" ~ "Female Sex",
                                        "INCOME" ~ "Family Income",
                                        "PARED" ~ "Parental Education",
                                        "SINGLE_PAR" ~ "Single Parent",
                                        "WHITE" ~ "White",
                                        "AFRICAN" ~ "African",
                                        "NATIVE" ~ "Native",
                                        "OTHER" ~ "Other Race",
                                        "HISPANIC" ~ "Hispanic",
                                        "PGSAGE" ~ "PGS x Age",
                                        "PGSSEX" ~ "PGS x Sex",
                                        "PGSINC" ~ "PGS x Income",
                                        "PGSPARED" ~ "PGS x Parental Education",
                                        "PGSSINGPAR" ~ "PGS x Single Parent",
                                        "SUB_HI_DUM" ~ "High SUB",
                                        "SUB_LO_DUM" ~ "Low SUB",
                                        "ASB_HI_DUM" ~ "High-Decline ASB",
                                        "ASB_MOD_DU" ~ "Moderate ASB",
                                        "ASB_ADO_DU"  ~ "Adolescent-Peaked ASB"
                                          ),
                     variable = factor(variable, c(
                                        "Supportive Parenting",
                                        "Delinquent Peer Affiliation",
                                        "School Connectedness",
                                        "Neighborhood Connectedness",
                                        "Total Effect",
                                        "Parent Indirect Effect",
                                        "Peer Indirect Effect",
                                        "School Indirect Effect",
                                        "Neighborhood Indirect Effect",
                                        "PGS Direct Effect",
                                        "PGS x Parent",
                                        "PGS x Peer",
                                        "PGS x School",
                                        "PGS x Neighborhood",
                                        "Age",
                                        "Female Sex",
                                        "Family Income",
                                        "Parental Education",
                                        "Single Parent",
                                        "White",
                                        "African",
                                        "Native",
                                        "Other Race",
                                        "Hispanic",
                                        "PGS x Age",
                                        "PGS x Sex",
                                        "PGS x Income",
                                        "PGS x Parental Education",
                                        "PGS x Single Parent",
                                        "High SUB",
                                        "Low SUB",
                                        "High-Decline ASB",
                                        "Moderate ASB",
                                        "Adolescent-Peaked ASB"

                     ))) 

```

## AFR table

```{r}
afr_apaths <- afr_apaths |> 
  mutate(outcome = factor(outcome,
                                    c("Supportive Parenting",
                                      "Delinquent Peer Affiliation",
                                      "School Connectedness",
                                      "Neighborhood Connectedness"
)),
                   est = if_else(lower*upper >= 0, 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "*"), 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "")),
                   lower = sprintf("%.3f", round(lower, digits = 3)),
                   upper = sprintf("%.3f", round(upper, digits = 3))
) |> arrange(outcome, variable)

afr_mainpaths <- afr_mainpaths |> 
  mutate(outcome = factor(outcome,
                                    c("High SUB",
                                      "Low SUB",
                                      "High-Decline ASB",
                                      "Moderate ASB",
                                      "Adolescent-Peaked ASB"
)),
                   est = exp(est),
                   lower = exp(lower),
                   upper = exp(upper),
                   est = if_else(log(lower)*log(upper) >= 0, 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "*"), 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "")),
                   lower = sprintf("%.3f", round(lower, digits = 3)),
                   upper = sprintf("%.3f", round(upper, digits = 3))
)|> arrange(outcome, variable)

write_csv(afr_apaths, "afr_apaths.csv")
write_csv(afr_mainpaths, "afr_mainpaths.csv")
```


# ASI

## Read in output

```{r}
asi <- readModels(here::here("analysis/rnr_asi.out"))$parameters$ci.unstandardized |> 
          as_tibble() |> janitor::clean_names() |> 
          select(param_header, param, est, low_5, up_5) |> 
          mutate(low_5 = as.numeric(replace(low_5, low_5 == "*********", "-9999")))

asi$param_header[312:336] <- rep(c("ASB#1.ON", "ASB#2.ON", "ASB#3.ON","SUB#1.ON", "SUB#2.ON"), each = 5)
asi <- asi |> mutate(param = replace(param, param %in% c("INDASB11","INDASB21",
                                                         "INDASB31","INDSUB11","INDSUB21"), 
                                     "Parent Indirect Effect"),
                     param = replace(param, param %in% c("INDASB12","INDASB22",
                                                         "INDASB32","INDSUB12","INDSUB22"), 
                                     "Peer Indirect Effect"),
                     param = replace(param, param %in% c("INDASB13","INDASB23",
                                                         "INDASB33","INDSUB13","INDSUB23"), 
                                     "School Indirect Effect"),
                     param = replace(param, param %in% c("INDASB14","INDASB24",
                                                         "INDASB34","INDSUB14","INDSUB24"), 
                                     "Neighborhood Indirect Effect"),
                     param = replace(param, param %in% c("TOTALASB","TOTALSUB"), 
                                     "Total Effect"))

asi_apaths <- asi |> filter(param_header %in% c("PARENT.ON", "PEER.ON", "SCHOOL.ON", "NEIGHBOR.ON"))

asi_mainpaths <- asi |> filter(param_header %in% c("ASB#1.ON", "ASB#2.ON", 
                                                   "ASB#3.ON","SUB#1.ON", "SUB#2.ON"))

```

## Process a paths

```{r}
asi_apaths <- asi_apaths |> 
              rename(outcome = "param_header", variable = "param", lower = "low_5", upper = "up_5") |> 
              mutate(outcome = case_match(outcome, 
                                               "PARENT.ON" ~ "Supportive Parenting", 
                                               "PEER.ON" ~ "Delinquent Peer Affiliation", 
                                               "SCHOOL.ON" ~ "School Connectedness", 
                                               "NEIGHBOR.ON" ~ "Neighborhood Connectedness"),
                     variable = case_match(variable,
                                        "AGE" ~ "Age",
                                        "SEX" ~ "Female Sex",
                                        "INCOME" ~ "Family Income",
                                        "PARED" ~ "Parental Education",
                                        "HISPANIC" ~ "Hispanic",
                                        "SINGLE_PAR" ~ "Single Parent",
                                        "PGS" ~ "PGS"),
                     variable = factor(variable, c("PGS", "Age", "Female Sex", "Family Income", "Parental Education", "Single Parent", "Hispanic"))) 

```


## Process main paths

```{r}
asi_mainpaths <- asi_mainpaths |> 
              rename(outcome = "param_header", variable = "param", lower = "low_5", upper = "up_5") |> 
              mutate(outcome = case_match(outcome, 
                                               "ASB#1.ON" ~ "High-Decline ASB", 
                                               "ASB#2.ON" ~ "Moderate ASB", 
                                               "ASB#3.ON" ~ "Adolescent-Peaked ASB", 
                                               "SUB#1.ON" ~ "High SUB",
                                               "SUB#2.ON" ~ "Low SUB"),
                     variable = case_match(variable,
                                        "PARENT" ~ "Supportive Parenting",
                                        "PEER" ~ "Delinquent Peer Affiliation",
                                        "SCHOOL" ~ "School Connectedness",
                                        "NEIGHBOR" ~ "Neighborhood Connectedness",
                                        "Total Effect" ~ "Total Effect",
                                        "Parent Indirect Effect" ~ "Parent Indirect Effect",
                                        "Peer Indirect Effect" ~ "Peer Indirect Effect",
                                        "School Indirect Effect" ~ "School Indirect Effect",
                                        "Neighborhood Indirect Effect" ~ "Neighborhood Indirect Effect",
                                        "PGS" ~ "PGS Direct Effect",
                                        "PGSPARENT" ~ "PGS x Parent",
                                        "PGSPEER" ~ "PGS x Peer",
                                        "PGSSCHOOL" ~ "PGS x School",
                                        "PGSNEIGHBO" ~ "PGS x Neighborhood",
                                        "AGE" ~ "Age",
                                        "SEX" ~ "Female Sex",
                                        "INCOME" ~ "Family Income",
                                        "PARED" ~ "Parental Education",
                                        "SINGLE_PAR" ~ "Single Parent",
                                        "HISPANIC" ~ "Hispanic",
                                        "PGSAGE" ~ "PGS x Age",
                                        "PGSSEX" ~ "PGS x Sex",
                                        "PGSINC" ~ "PGS x Income",
                                        "PGSPARED" ~ "PGS x Parental Education",
                                        "PGSSINGPAR" ~ "PGS x Single Parent",
                                        "SUB_HI_DUM" ~ "High SUB",
                                        "SUB_LO_DUM" ~ "Low SUB",
                                        "ASB_HI_DUM" ~ "High-Decline ASB",
                                        "ASB_MOD_DU" ~ "Moderate ASB",
                                        "ASB_ADO_DU"  ~ "Adolescent-Peaked ASB"
                                          ),
                     variable = factor(variable, c(
                                        "Supportive Parenting",
                                        "Delinquent Peer Affiliation",
                                        "School Connectedness",
                                        "Neighborhood Connectedness",
                                        "Total Effect",
                                        "Parent Indirect Effect",
                                        "Peer Indirect Effect",
                                        "School Indirect Effect",
                                        "Neighborhood Indirect Effect",
                                        "PGS Direct Effect",
                                        "PGS x Parent",
                                        "PGS x Peer",
                                        "PGS x School",
                                        "PGS x Neighborhood",
                                        "Age",
                                        "Female Sex",
                                        "Family Income",
                                        "Parental Education",
                                        "Single Parent",
                                        "Hispanic",
                                        "PGS x Age",
                                        "PGS x Sex",
                                        "PGS x Income",
                                        "PGS x Parental Education",
                                        "PGS x Single Parent",
                                        "High SUB",
                                        "Low SUB",
                                        "High-Decline ASB",
                                        "Moderate ASB",
                                        "Adolescent-Peaked ASB"

                     ))) 

```

## ASI table

```{r}
asi_apaths <- asi_apaths |> 
  mutate(outcome = factor(outcome,
                                    c("Supportive Parenting",
                                      "Delinquent Peer Affiliation",
                                      "School Connectedness",
                                      "Neighborhood Connectedness"
)),
                   est = if_else(lower*upper >= 0, 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "*"), 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "")),
                   lower = sprintf("%.3f", round(lower, digits = 3)),
                   upper = sprintf("%.3f", round(upper, digits = 3))
) |> arrange(outcome, variable)

asi_mainpaths <- asi_mainpaths |> 
  mutate(outcome = factor(outcome,
                                    c("High SUB",
                                      "Low SUB",
                                      "High-Decline ASB",
                                      "Moderate ASB",
                                      "Adolescent-Peaked ASB"
)),
                   est = exp(est),
                   lower = exp(lower),
                   upper = exp(upper),
                   est = if_else(log(lower)*log(upper) >= 0, 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "*"), 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "")),
                   lower = sprintf("%.3f", round(lower, digits = 3)),
                   upper = sprintf("%.3f", round(upper, digits = 3))
)|> arrange(outcome, variable)

write_csv(asi_apaths, "asi_apaths.csv")
write_csv(asi_mainpaths, "asi_mainpaths.csv")
```



# HIS

## Read in output

```{r}
his <- readModels(here::here("analysis/rnr_his.out"))$parameters$ci.unstandardized |> 
          as_tibble() |> janitor::clean_names() |> 
          select(param_header, param, est, low_5, up_5)|> 
          mutate(low_5 = as.numeric(replace(low_5, low_5 == "*********", "-9999")))

his$param_header[426:450] <- rep(c("ASB#1.ON", "ASB#2.ON", "ASB#3.ON","SUB#1.ON", "SUB#2.ON"), each = 5)
his <- his |> mutate(param = replace(param, param %in% c("INDASB11","INDASB21",
                                                         "INDASB31","INDSUB11","INDSUB21"), 
                                     "Parent Indirect Effect"),
                     param = replace(param, param %in% c("INDASB12","INDASB22",
                                                         "INDASB32","INDSUB12","INDSUB22"), 
                                     "Peer Indirect Effect"),
                     param = replace(param, param %in% c("INDASB13","INDASB23",
                                                         "INDASB33","INDSUB13","INDSUB23"), 
                                     "School Indirect Effect"),
                     param = replace(param, param %in% c("INDASB14","INDASB24",
                                                         "INDASB34","INDSUB14","INDSUB24"), 
                                     "Neighborhood Indirect Effect"),
                     param = replace(param, param %in% c("TOTALASB","TOTALSUB"), 
                                     "Total Effect"))

his_apaths <- his |> filter(param_header %in% c("PARENT.ON", "PEER.ON", "SCHOOL.ON", "NEIGHBOR.ON"))

his_mainpaths <- his |> filter(param_header %in% c("ASB#1.ON", "ASB#2.ON", 
                                                   "ASB#3.ON","SUB#1.ON", "SUB#2.ON"))

```

## Process a paths

```{r}
his_apaths <- his_apaths |> 
              rename(outcome = "param_header", variable = "param", lower = "low_5", upper = "up_5") |> 
              mutate(outcome = case_match(outcome, 
                                               "PARENT.ON" ~ "Supportive Parenting", 
                                               "PEER.ON" ~ "Delinquent Peer Affiliation", 
                                               "SCHOOL.ON" ~ "School Connectedness", 
                                               "NEIGHBOR.ON" ~ "Neighborhood Connectedness"),
                     variable = case_match(variable,
                                        "AGE" ~ "Age",
                                        "SEX" ~ "Female Sex",
                                        "INCOME" ~ "Family Income",
                                        "PARED" ~ "Parental Education",
                                        "WHITE" ~ "White",
                                        "NATIVE" ~ "Native",
                                        "ASIAN" ~ "Asian", 
                                        "OTHER" ~ "Other Race",
                                        "HISPANIC" ~ "Hispanic",
                                        "SINGLE_PAR" ~ "Single Parent",
                                        "PGS" ~ "PGS"),
                     variable = factor(variable, c("PGS", "Age", "Female Sex", "Family Income", "Parental Education", "Single Parent","White", "Native", "Asian", "Other Race", "Hispanic"))) 

```


## Process main paths

```{r}
his_mainpaths <- his_mainpaths |> 
              rename(outcome = "param_header", variable = "param", lower = "low_5", upper = "up_5") |> 
              mutate(outcome = case_match(outcome, 
                                               "ASB#1.ON" ~ "High-Decline ASB", 
                                               "ASB#2.ON" ~ "Moderate ASB", 
                                               "ASB#3.ON" ~ "Adolescent-Peaked ASB", 
                                               "SUB#1.ON" ~ "High SUB",
                                               "SUB#2.ON" ~ "Low SUB"),
                     variable = case_match(variable,
                                        "PARENT" ~ "Supportive Parenting",
                                        "PEER" ~ "Delinquent Peer Affiliation",
                                        "SCHOOL" ~ "School Connectedness",
                                        "NEIGHBOR" ~ "Neighborhood Connectedness",
                                        "Total Effect" ~ "Total Effect",
                                        "Parent Indirect Effect" ~ "Parent Indirect Effect",
                                        "Peer Indirect Effect" ~ "Peer Indirect Effect",
                                        "School Indirect Effect" ~ "School Indirect Effect",
                                        "Neighborhood Indirect Effect" ~ "Neighborhood Indirect Effect",
                                        "PGS" ~ "PGS Direct Effect",
                                        "PGSPARENT" ~ "PGS x Parent",
                                        "PGSPEER" ~ "PGS x Peer",
                                        "PGSSCHOOL" ~ "PGS x School",
                                        "PGSNEIGHBO" ~ "PGS x Neighborhood",
                                        "AGE" ~ "Age",
                                        "SEX" ~ "Female Sex",
                                        "INCOME" ~ "Family Income",
                                        "PARED" ~ "Parental Education",
                                        "SINGLE_PAR" ~ "Single Parent",
                                        "WHITE" ~ "White",
                                        "NATIVE" ~ "Native",
                                        "ASIAN" ~ "Asian", 
                                        "OTHER" ~ "Other Race",
                                        "HISPANIC" ~ "Hispanic",
                                        "PGSAGE" ~ "PGS x Age",
                                        "PGSSEX" ~ "PGS x Sex",
                                        "PGSINC" ~ "PGS x Income",
                                        "PGSPARED" ~ "PGS x Parental Education",
                                        "PGSSINGPAR" ~ "PGS x Single Parent",
                                        "SUB_HI_DUM" ~ "High SUB",
                                        "SUB_LO_DUM" ~ "Low SUB",
                                        "ASB_HI_DUM" ~ "High-Decline ASB",
                                        "ASB_MOD_DU" ~ "Moderate ASB",
                                        "ASB_ADO_DU"  ~ "Adolescent-Peaked ASB"
                                          ),
                     variable = factor(variable, c(
                                        "Supportive Parenting",
                                        "Delinquent Peer Affiliation",
                                        "School Connectedness",
                                        "Neighborhood Connectedness",
                                        "Total Effect",
                                        "Parent Indirect Effect",
                                        "Peer Indirect Effect",
                                        "School Indirect Effect",
                                        "Neighborhood Indirect Effect",
                                        "PGS Direct Effect",
                                        "PGS x Parent",
                                        "PGS x Peer",
                                        "PGS x School",
                                        "PGS x Neighborhood",
                                        "Age",
                                        "Female Sex",
                                        "Family Income",
                                        "Parental Education",
                                        "Single Parent",
                                        "White",
                                        "Native",
                                        "Asian",
                                        "Other Race",
                                        "Hispanic",
                                        "PGS x Age",
                                        "PGS x Sex",
                                        "PGS x Income",
                                        "PGS x Parental Education",
                                        "PGS x Single Parent",
                                        "High SUB",
                                        "Low SUB",
                                        "High-Decline ASB",
                                        "Moderate ASB",
                                        "Adolescent-Peaked ASB"

                     ))) 

```

## HIS table

```{r}
his_apaths <- his_apaths |> 
  mutate(outcome = factor(outcome,
                                    c("Supportive Parenting",
                                      "Delinquent Peer Affiliation",
                                      "School Connectedness",
                                      "Neighborhood Connectedness"
)),
                   est = if_else(lower*upper >= 0, 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "*"), 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "")),
                   lower = sprintf("%.3f", round(lower, digits = 3)),
                   upper = sprintf("%.3f", round(upper, digits = 3))
) |> arrange(outcome, variable)

his_mainpaths <- his_mainpaths |> 
  mutate(outcome = factor(outcome,
                                    c("High SUB",
                                      "Low SUB",
                                      "High-Decline ASB",
                                      "Moderate ASB",
                                      "Adolescent-Peaked ASB"
)),
                   est = exp(est),
                   lower = exp(lower),
                   upper = exp(upper),
                   est = if_else(log(lower)*log(upper) >= 0, 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "*"), 
                                 paste0(sprintf("%.3f", round(est, digits = 3)), "")),
                   lower = sprintf("%.3f", round(lower, digits = 3)),
                   upper = sprintf("%.3f", round(upper, digits = 3))
)|> arrange(outcome, variable)

write_csv(his_apaths, "his_apaths.csv")
write_csv(his_mainpaths, "his_mainpaths.csv")
```

